apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: dbone-dev:/Service:team1/dbone-mariadb
  labels:
    app: dbone-database
  name: dbone-mariadb
  namespace: team1
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: dbone-data