apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: team1-mongodb-secrets
  namespace: team1
spec:
  vaultAuthRef: vaultauth-team1
  type: kv-v2
  mount: k3s              # change to your KV mount name (often "secret" or "kv")
  path: env_shared/infra/mongo_data
  refreshAfter: 1m
  destination:
    create: true
    name: mongodb-secrets  # Kubernetes Secret name to get