apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app8
  namespace: argocd
  labels:
    team: k3s-admin
    app.kubernetes.io/name: app8
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: team1
  annotations:
    #argocd.argoproj.io/sync-wave: "0"
    description: "ApplicationSet for app8 deployment"
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
        - key: env
          operator: In
          values: [prod, test, dev]
  template:
    metadata:
      name: "app8-{{metadata.labels.env}}"
      namespace: argocd
      labels:
        app.kubernetes.io/name: app8
        app.kubernetes.io/instance: "app8-{{metadata.labels.env}}"
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/part-of: team1
        environment: "{{metadata.labels.env}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: apps
      sources:
        # Source 1: watch python source code repo — commit SHA injected as helm param
        - $APP_SOME_GH_REPOSITORY-app8.git
          targetRevision: "{{metadata.labels.appGitBranch}}"
          ref: pciToolSrc
        # Source 2: helm chart from infra repo
        - $APP_SOME_GH_REPOSITORY-k3s_deployment.git
          targetRevision: "{{metadata.labels.env}}"
          path: argocd/team1/charts/app8
          helm:
            valueFiles:
              - values/common.yaml
              - "values/{{metadata.labels.env}}.yaml"
            parameters:
              - name: global.srcRevision
                value: $pciToolSrc
      destination:
        server: "{{server}}"
        namespace: team1
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
