---
# Source: gha-runner-scale-set/templates/kube_mode_serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k3s-self-hosted-gha-rs-kube-mode
  namespace: arc-runners
  finalizers:
    - actions.github.com/cleanup-protection
  labels:
    helm.sh/chart: gha-rs-0.9.3
    app.kubernetes.io/name: k3s-self-hosted
    app.kubernetes.io/instance: k3s-self-hosted
    app.kubernetes.io/version: "0.9.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: k3s-self-hosted
    actions.github.com/scale-set-namespace: arc-runners
---
# Source: gha-runner-scale-set/templates/kube_mode_role.yaml
# default permission for runner pod service account in kubernetes mode (container hook)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k3s-self-hosted-gha-rs-kube-mode
  namespace: arc-runners
  finalizers:
    - actions.github.com/cleanup-protection
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch",]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
---
# Source: gha-runner-scale-set/templates/manager_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k3s-self-hosted-gha-rs-manager
  namespace: arc-runners
  labels:
    helm.sh/chart: gha-rs-0.9.3
    app.kubernetes.io/name: k3s-self-hosted
    app.kubernetes.io/instance: k3s-self-hosted
    app.kubernetes.io/version: "0.9.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: k3s-self-hosted
    actions.github.com/scale-set-namespace: arc-runners
    app.kubernetes.io/component: manager-role
  finalizers:
    - actions.github.com/cleanup-protection
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
# Source: gha-runner-scale-set/templates/kube_mode_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k3s-self-hosted-gha-rs-kube-mode
  namespace: arc-runners
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k3s-self-hosted-gha-rs-kube-mode
subjects:
- kind: ServiceAccount
  name: k3s-self-hosted-gha-rs-kube-mode
  namespace: arc-runners
---
# Source: gha-runner-scale-set/templates/manager_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k3s-self-hosted-gha-rs-manager
  namespace: arc-runners
  labels:
    helm.sh/chart: gha-rs-0.9.3
    app.kubernetes.io/name: k3s-self-hosted
    app.kubernetes.io/instance: k3s-self-hosted
    app.kubernetes.io/version: "0.9.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: k3s-self-hosted
    actions.github.com/scale-set-namespace: arc-runners
    app.kubernetes.io/component: manager-role-binding
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k3s-self-hosted-gha-rs-manager
subjects:
- kind: ServiceAccount
  name: 
    actions-runner-controller-gha-rs-controller
  namespace: 
    arc-systems
---
# Source: gha-runner-scale-set/templates/autoscalingrunnerset.yaml
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: k3s-self-hosted
  namespace: arc-runners
  labels:
    app.kubernetes.io/component: "autoscaling-runner-set"
    helm.sh/chart: gha-rs-0.9.3
    app.kubernetes.io/name: k3s-self-hosted
    app.kubernetes.io/instance: k3s-self-hosted
    app.kubernetes.io/version: "0.9.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: k3s-self-hosted
    actions.github.com/scale-set-namespace: arc-runners
  annotations:
    actions.github.com/values-hash: b0d5bece6e011177efdd7cda5ebd2acc17aa6ff3b86c8a0c13f00cc8c64fe77
    actions.github.com/cleanup-manager-role-binding: k3s-self-hosted-gha-rs-manager
    actions.github.com/cleanup-manager-role-name: k3s-self-hosted-gha-rs-manager
    actions.github.com/cleanup-kubernetes-mode-role-binding-name: k3s-self-hosted-gha-rs-kube-mode
    actions.github.com/cleanup-kubernetes-mode-role-name: k3s-self-hosted-gha-rs-kube-mode
    actions.github.com/cleanup-kubernetes-mode-service-account-name: k3s-self-hosted-gha-rs-kube-mode
spec:
  githubConfigUrl: https://$PRIVATE_GH_FQDN/infrateam-k3s_deployment
  githubConfigSecret: arc-github-secret
  runnerScaleSetName: k3s-self-hosted
  maxRunners: 5
  minRunners: 0
  listenerTemplate:
    spec:
      hostAliases:
      - ip: "$IP_ADDR2"
        hostnames:
        - "github.web..com"
      containers:
      - name: listener
        image: $ARTIFACTORY/$ARTIFACTORY_SUB_PATH/actions/gha-runner-scale-set-controller:0.9.3

  template:
    spec:
      hostAliases:
      - ip: "$IP_ADDR2"
        hostnames:
        - "github.web..com"
      restartPolicy: Never
      serviceAccountName: k3s-self-hosted-gha-rs-kube-mode
      containers:
      - name: runner
        
        command: 
          - /home/runner/run.sh
        image: $ARTIFACTORY/$ARTIFACTORY_SUB_PATH/actions/actions-runner:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOKS
            value: /home/runner/k8s/index.js
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
      
      volumes:
      
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              storageClassName: local-path
              resources:
                requests:
                  storage: 1Gi
