apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: {{ .Values.namespace }}
data:
  vault-cfg.hcl: |
    ui = true
    disable_mlock = true
    api_addr      = "https://{{ index .Values "vault-cfg" "NODE_ID" }}:30820"
    cluster_addr  = "https://{{ index .Values "vault-cfg" "NODE_ID" }}:30821"
    default_lease_ttl = "140h"
    max_lease_ttl = "720h"
    log_level     = "debug"
    log_format    = "json"

    listener "tcp" {
      address         = "0.0.0.0:8220"
      cluster_address = "0.0.0.0:8221"
      tls_disable = "false"
      tls_cert_file      = "/vault/config/tls.crt"
      tls_key_file       = "/vault/config/tls.key"
      tls_client_ca_file = "/vault/config/vault-ca.pem"
      tls_min_version = "tls12"
      tls_cipher_suites = "TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384"  
    }

    storage "raft" {
    "path" = "/vault/data"
    "node_id" = "{{ index .Values "vault-cfg" "NODE_ID" }}"
    "tls_disable" = "false"

    retry_join {
        leader_tls_servername   = "{{ index .Values "vault-cfg" "NODE_VAULT_PEER1" }}"
        leader_api_addr         = "https://{{ index .Values "vault-cfg" "NODE_VAULT_PEER1" }}:8200"
        leader_ca_cert_file     = "/vault/config/vault-ca.pem"
        tls_cert_file      = "/vault/config/tls.crt"
        tls_key_file       = "/vault/config/tls.key"
        tls_client_ca_file = "/vault/config/vault-ca.pem"
    }
    retry_join {
        leader_tls_servername   = "{{ index .Values "vault-cfg" "NODE_VAULT_PEER2" }}"
        leader_api_addr         = "https://{{ index .Values "vault-cfg" "NODE_VAULT_PEER2" }}:30820"
        leader_ca_cert_file     = "/vault/config/vault-ca.pem"
        tls_cert_file      = "/vault/config/tls.crt"
        tls_key_file       = "/vault/config/tls.key"
        tls_client_ca_file = "/vault/config/vault-ca.pem"
    }
    retry_join {
        leader_tls_servername   = "{{ index .Values "vault-cfg" "NODE_VAULT_PEER3" }}"
        leader_api_addr         = "https://{{ index .Values "vault-cfg" "NODE_VAULT_PEER3" }}:8200"
        leader_ca_cert_file     = "/vault/config/vault-ca.pem"
        tls_cert_file      = "/vault/config/tls.crt"
        tls_key_file       = "/vault/config/tls.key"
        tls_client_ca_file = "/vault/config/vault-ca.pem"
    }

    autopilot {
        cleanup_dead_servers = "true"
        last_contact_threshold = "200ms"
        last_contact_failure_threshold = "1m"
        max_trailing_logs = 250000
        min_quorum = 3
        server_stabilization_time = "10s"
    }

    }

    
