apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: team1
---
apiVersion: v1
kind: Namespace
metadata:
  name: team2
---
apiVersion: v1
kind: Namespace
metadata:
  name: team3
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems