apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: team1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: team2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: arc-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-tokenreview
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-tokenreview
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: kube-system
  - kind: ServiceAccount
    name: vault-auth
    namespace: monitoring
  - kind: ServiceAccount
    name: vault-auth
    namespace: logging
  - kind: ServiceAccount
    name: vault-auth
    namespace: team1
  - kind: ServiceAccount
    name: vault-auth
    namespace: team2
  - kind: ServiceAccount
    name: vault-auth
    namespace: arc-runners
  - kind: ServiceAccount
    name: vault-auth
    namespace: argocd