apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vaultauth-argocd
  namespace: argocd
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes-dev
  kubernetes:
    role: k3s-auth
    serviceAccount: vault-auth