# infra/argocd/app-of-apps-team1.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps-vulcan
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
        - key: env
          operator: In
          values: [test, dev, prod]
  template:
    metadata:
      name: "app-of-apps-vulcan-{{metadata.labels.env}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        $APP_SOME_GH_REPOSITORY-k3s_deployment.git
        targetRevision: "{{metadata.labels.env}}"
        path: argocd/apps/vulcan
      destination:
        server: "{{server}}"
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true