apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vaultauth-team1
  namespace: team1
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes-prod-la
  kubernetes:
    role: k3s-auth
    serviceAccount: vault-auth