apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: arc-github-secret
  namespace: arc-runners
spec:
  vaultAuthRef: vaultauth-arc-runners
  type: kv-v2
  mount: k3s
  path: env_shared/infra/$TOOLING_ACCOUNT_ID_PGH_PAT_RUNNER
  refreshAfter: 1m
  destination:
    create: true
    name: arc-github-secret  # Kubernetes Secret name
    labels:
      argocd.argoproj.io/secret-type: repo-creds