apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-repo-creds-github-dmz
  namespace: argocd
spec:
  vaultAuthRef: vaultauth-argocd
  type: kv-v2
  mount: infrateam
  path: github_dmz/$TOOLING_ACCOUNT_ID_itservices_id_rsa
  refreshAfter: 1m
  destination:
    create: true
    name: argocd-repo-creds-github-dmz  # Kubernetes Secret name
    labels:
      argocd.argoproj.io/secret-type: repo-creds