apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kube-system-proxysql-secrets
  namespace: kube-system
spec:
  vaultAuthRef: vaultauth-kube-system
  type: kv-v2
  mount: k3s              # change to your KV mount name (often "secret" or "kv")
  path: env_shared/infra/proxysql
  refreshAfter: 1m
  destination:
    create: true
    name: proxysql-secrets  # Kubernetes Secret name to get