apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-secret
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: vaultauth-monitoring
  type: kv-v2
  mount: k3s
  path: env_shared/infra/grafana
  refreshAfter: 1m
  destination:
    create: true
    name: grafana-admin-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app6-db-secret
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: vaultauth-monitoring
  type: kv-v2
  mount: infrateam
  path: database/dcu/app6/prod
  refreshAfter: 1m
  destination:
    create: true
    name: app6-db-secret